#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# jdk 17
FROM --platform=$BUILDPLATFORM centos:8.4.2105 AS builder

#RUN export https_proxy=http://docker.for.mac.localhost:6152 \
#    && export http_proxy=http://docker.for.mac.localhost:6152 \
#    && export all_proxy=socks5://docker.for.mac.localhost:6153

RUN cd /etc/yum.repos.d/ \
    && sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* \
    && yum install -y java-17-openjdk-devel wget telnet git openssl \
    && yum clean all -y

# install maven
ARG MAVEN_VERSION=3.9.3
ARG MAVEN_DOWNLOAD_URL=https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
    && wget -O /tmp/apache-maven.tar.gz ${MAVEN_DOWNLOAD_URL} --no-check-certificate \
    && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
    && rm -f /tmp/apache-maven.tar.gz \
    && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

### make it faster if remove those "#"s bellow
#RUN sed -i '159i \
#     <mirror> \
#       <id>nexus-tencentyun</id> \
#       <mirrorOf>*</mirrorOf> \
#       <name>Nexus tencentyun</name> \
#       <url>http://mirrors.tencent.com/nexus/repository/maven-public/</url> \
#     </mirror> \
# ' /usr/share/maven/conf/settings.xml

RUN cat /usr/share/maven/conf/settings.xml \
    && mkdir -p /root/.m2/repository \
    && cp -f /usr/share/maven/conf/settings.xml /root/.m2/settings.xml

# compile
# https://ghproxy.com/
RUN git clone -b master --single-branch https://ghproxy.com/https://github.com/apache/rocketmq-dashboard.git /tmp/rocketmq-dashboard \
    && cd /tmp/rocketmq-dashboard \
    && mvn -s /usr/share/maven/conf/settings.xml -DskipTests clean install \
    && ls -l target

#RUN rm -rf /root/.m2/repository/* \
#    && rm -rf /usr/share/maven \
#    && rm -rf /tmp/rocketmq-dashboard \
#    && yum remove git openssl -y

FROM --platform=$BUILDPLATFORM centos:8.4.2105

# RocketMQ Dashboard runs with user `rocketmq`, uid = 3000
# If you bind mount a volume from the host or a data container,
# ensure you use the same uid
ARG user=rocketmq
ARG group=rocketmq
ARG uid=3000
ARG gid=3000

ARG version

ENV ROCKETMQ_DASHBOARD_VERSION ${version}
ENV ROCKETMQ_DASHBOARD_HOME /home/rocketmq/rocketmq-dashboard-${ROCKETMQ_DASHBOARD_VERSION}
WORKDIR ${ROCKETMQ_DASHBOARD_HOME}

RUN cd /etc/yum.repos.d/ \
    && sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* \
    && yum install -y java-17-openjdk-headless vi telnet \
    && yum clean all -y \
    && groupadd -g ${gid} ${group} \
    && useradd -u ${uid} -g ${gid} -m -s /bin/bash ${user} \
    && mkdir -p $ROCKETMQ_DASHBOARD_HOME/bin \
    && chown -R ${uid}:${gid} /home/rocketmq

COPY --from=builder --chown=${uid}:${gid} /tmp/rocketmq-dashboard/target/rocketmq-dashboard-1.0.1-SNAPSHOT.jar $ROCKETMQ_DASHBOARD_HOME/bin/rocketmq-dashboard.jar

USER ${user}

EXPOSE 8080

#ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar bin/rocketmq-dashboard.jar"]
CMD ["/bin/sh"]