#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM --platform=$BUILDPLATFORM centos:8.4.2105 as builder

ARG version

# Rocketmq version
ENV ROCKETMQ_VERSION ${version}

# Rocketmq home
#ENV ROCKETMQ_HOME  /home/rocketmq/rocketmq-${ROCKETMQ_VERSION}
ENV ROCKETMQ_HOME  /home/rocketmq
WORKDIR ${ROCKETMQ_HOME}

RUN cd /etc/yum.repos.d/ \
    && sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* \
    && yum install -y java-17-openjdk-devel unzip openssl which gnupg telnet \
    && yum clean all -y

RUN set -eux; \
    curl -L https://archive.apache.org/dist/rocketmq/${ROCKETMQ_VERSION}/rocketmq-all-${ROCKETMQ_VERSION}-bin-release.zip -o rocketmq.zip; \
    curl -L https://archive.apache.org/dist/rocketmq/${ROCKETMQ_VERSION}/rocketmq-all-${ROCKETMQ_VERSION}-bin-release.zip.asc -o rocketmq.zip.asc; \
	curl -L https://www.apache.org/dist/rocketmq/KEYS -o KEYS; \
	gpg --import KEYS; \
    gpg --batch --verify rocketmq.zip.asc rocketmq.zip ; \
    unzip rocketmq.zip ; \
	mv rocketmq*/* . ; \
	rmdir rocketmq-*  ; \
	rm rocketmq.zip rocketmq.zip.asc KEYS

RUN mkdir -p ${ROCKETMQ_HOME}/conf/acl

FROM centos:8.4.2105

ARG user=rocketmq
ARG group=rocketmq
ARG uid=3000
ARG gid=3000

# Rocketmq home
ARG version
ENV ROCKETMQ_VERSION ${version}
ENV ROCKETMQ_HOME /home/rocketmq
ENV JAVA_HOME=/usr/lib/jvm/jre-17-openjdk
ENV PATH=$PATH:${JAVA_HOME}/bin

# add scripts
#--chown=${uid}:${gid}
COPY scripts/docker-entrypoint.sh ${ROCKETMQ_HOME}/bin/
COPY --from=builder ${ROCKETMQ_HOME}/. ${ROCKETMQ_HOME}

# RocketMQ is run with user `rocketmq`, uid = 3000
# If you bind mount a volume from the host or a data container,
# ensure you use the same uid
RUN cd /etc/yum.repos.d/ \
    && sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* \
    && yum install -y java-17-openjdk-headless vi telnet \
    && yum clean all -y \
    && groupadd -g ${gid} ${group} \
    && useradd -u ${uid} -g ${gid} -m -s /bin/bash ${user} \
    && mkdir -p /home/rocketmq/logs \
    && mkdir -p /home/rocketmq/store \
    && chown -R rocketmq:rocketmq /home/rocketmq \
    && chmod -R a+x ${ROCKETMQ_HOME}/bin/ \
    && export JAVA_OPT=" -Duser.home=/opt" \
    && sed -i 's/${JAVA_HOME}\/jre\/lib\/ext/${JAVA_HOME}\/jre\/lib\/ext:${JAVA_HOME}\/lib\/ext/' ${ROCKETMQ_HOME}/bin/tools.sh

# expose namesrv port
EXPOSE 9876 9878

# expose proxy port
EXPOSE 8080 8081

# expose broker ports
EXPOSE 10909 10911 10912

USER ${user}

WORKDIR ${ROCKETMQ_HOME}/bin

ENTRYPOINT ["./docker-entrypoint.sh"]

CMD ["/bin/sh"]
